site_name: ESP32 IoT Documentation
site_description: ESP32 Environmental Monitor Documentation

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Hardware Setup: hardware.md
  - MQTT Guide: mqtt.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - tables

plugins:
  - search
